### ISSUE TITLE
Debug log warning when using customizer with Ocean WP

### ISSUE THREAD

**Issue by blinkcursor** [oceanwp/oceanwp#16] opened 2017-08-10 11:28 UTC
I get this PHP warning in debug.log if I open the theme customizer while using Ocean WP:

`PHP Notice:  Array to string conversion in .../wp-includes/formatting.php on line 1031`

I don't get the error if I, for example, open customizer when twentyseventeen is active.

**Comment by oceanwp** [comment] 2017-08-10 13:27
Hello, are you on Firefox?
Because there is a problem with this browser and the customizer if there are many options. You should simply click to no longer display this message and click the Continue button.

**Comment by blinkcursor** [comment] 2017-08-10 13:27
Nope. This is using Chrome on Mac.

**Comment by oceanwp** [comment] 2017-08-10 13:34
Hi, I'm on Chrome too and I've never see this issue. Have you tried to disable all your plugins to see if there is a conflict?

**Comment by blinkcursor** [comment] 2017-08-10 13:45
I disabled all plugins and got the same result.

So I just downloaded WP 4.8.1 from wp.org and made a clean install.

The only thing I did was to install OceanWP then activate it.

When I open the customizer on the front-end, before I try to make or save any changes, that PHP warning appears in the debug.log.

I have switched between PHP 7.0.10 and 5.6.25 to see if that changes anything (it doesn't).

I reverted to twentyseventeen and opened the customizer again, this time no warning.

I was alerted to this by a colleague who asked me to investigate, so it is not unique to me.

**Comment by oceanwp** [comment] 2017-08-10 14:07
That's pretty weird, have you tried with a theme who has many options in the customizer?
Because TwentySeventeen have not many options, so to see if the problem come from there, try with a theme who have a lot of customizer options and look at if you have the same issue.

**Comment by blinkcursor** [comment] 2017-08-10 14:12
I just tried with GeneratePress and Astra themes, and neither generate the PHP warning.

If you are able to reproduce, perhaps you can debug?

**Comment by oceanwp** [comment] 2017-08-10 14:54
I would like to reproduce it but I don't have this issue.
When I go to the customizer page, I have no problem and I use PHP 7.1, I also tried with PHP 7.0, no problem either.

**Comment by blinkcursor** [comment] 2017-08-10 20:50
You want me to send you a duplicator package?

**Comment by oceanwp** [comment] 2017-08-10 21:34
That would be great yes, I could see if there is the same issue on my site.

**Comment by blinkcursor** [comment] 2017-08-11 07:24
Here you go: https://drive.google.com/open?id=0B3w-tBaqecWHZXdpWGhaZGdQbkk

**Comment by oceanwp** [comment] 2017-08-11 14:03
Hi, thanks but how do I import on my site? I use the "All-in-One WP Migration" to import/export site with database.
Question, have you tried on a different site?

**Comment by blinkcursor** [comment] 2017-08-11 14:14
It's a duplicator package: https://wordpress.org/plugins/duplicator/

There is a short explanatory video on that page.

It makes an exact copy of the entire site, you install it in an empty directory and start the process by visiting installer.php in your browser, e.g. localhost/t-oceanwp/installer.php

You just need to tell it the name of the database it should create and the db username/password that will be added in wp-config.php (e.g. root/root).

Have I tried it on a different site?

Yes. My colleague tried it on one site and alerted me to the problem.

I tested it on a local site with OceanWP and reproduced the problem.

I then created a fresh install as described above to test just this issue, and it is this vanilla site I have duplicated for you.

**Comment by oceanwp** [comment] 2017-08-11 14:16
Okay, I try with this plugin

**Comment by oceanwp** [comment] 2017-08-11 14:49
Hi, I have imported the site and the database and when I go into the customizer, I have no PHP error, everything works perfectly.
Sorry but I do not know at all why you have this error.

**Comment by blinkcursor** [comment] 2017-08-11 15:12
No warning added to the debug.log file in wp-content?

OK, in which case I don't know what to say, either. I'm using MAMP for my server, it may be something specific to do with the server settings.

Maybe leave the issue open for a few days in case anyone else comments, and if not, close it?

**Comment by oceanwp** [comment] 2017-08-11 15:15
No, no warning, everything is normal.
I use XAMPP, it is possible the issue come from the server.
Sure, I leave the issue open a few days.

**Comment by oceanwp** [comment] 2017-10-13 20:28
Hello, I close this topic as no one else seem to have this issue.
Feel free to open another topic if you have an issue.

**Closed by oceanwp** 2017-10-13 20:28 UTC
