### ISSUE TITLE
Double Stepper

### ISSUE THREAD

**Issue by deebz** [oceanwp/oceanwp#338] opened 2021-07-20 11:21 UTC
I just updated to OceanWP 3.0.0 and now see double steppers. Interestingly the steppers step up increments by 2 each time.

I also updated the ocean extra and ocean social plugins at the same time. Once I spotted the bug I then downgraded plugins and theme and added the plugins back one by one. The issue only occurred once I upgraded the theme.

<img width="268" alt="Screenshot 2021-07-20 at 11 52 25" src="https://user-images.githubusercontent.com/462011/126315200-e25f758e-7572-407a-900d-768b56619777.png">

**Comment by MarkHollo** [comment] 2021-07-21 08:12
Hello @deebz,

This problem was reported by a couple of our users and is caching related. Please make sure to clear ALL caching (website/browser/cloud) thoroughly.

I would also recommend [checking out this post for more details on the new changes](https://oceanwp.org/blog/oceanwp-3-this-summer-is-all-about-vanilla-js/), as well as how to prepare your website for the update.

Let us know if you're still experiencing problems on your end

**Comment by MarkHollo** [comment] 2021-07-22 11:30
Since the problem was confirmed as resolved after clearing cache by users who experienced the same, I'm closing this thread. In case you are still experiencing problems, please feel free to reopen this or start a new thread.

Thank you and wishing you an amazing day

**Closed by MarkHollo** 2021-07-22 11:30 UTC
