### ISSUE TITLE
Oceans Extra

### ISSUE THREAD

**Issue by archwebdesign** [oceanwp/oceanwp#339] opened 2021-07-20 21:11 UTC
Following the update

Cannot edit Elementor pages
Elementor popups no longer work.
Double - and + on product quantity incrementing by 2

Disabling Oceans Extra removes the problems

**Comment by MarkHollo** [comment] 2021-07-21 08:14
Hello @archwebdesign,

Make sure all scripts are enabled via Theme Panel > Scripts & Styles.

After that, purge ALL caching (website, cloud, browser) multiple times if necessary.

I would also recommend [checking out this article for more information](https://oceanwp.org/blog/oceanwp-3-this-summer-is-all-about-vanilla-js/).

Let us know if you're still experiencing problems.

**Comment by MarkHollo** [comment] 2021-07-22 11:31
Since the problem was confirmed as resolved after clearing cache by users who experienced the same, I'm closing this thread. In case you are still experiencing problems, please feel free to reopen this or start a new thread.

Thank you and wishing you an amazing day

**Closed by MarkHollo** 2021-07-22 11:31 UTC
