### ISSUE TITLE
Check in check boxes fail to load

### ISSUE THREAD

**Issue by Okkx** [oceanwp/oceanwp#233] opened 2019-11-14 13:33 UTC
Hello,

I'm sorry but I have to open this issue again, after extensive testing with OceanWP 1.7.3, on many devices, with cable internet, or wifi, or 4G network with freshly installed browsers, on desktop or mobile, without any cache activated, some characters are still not displayed correctly on 1.7.3 with Ocean Extra 1.5.19 (also happened with 17.2 and Ocean Extra 1.5.18).

My tests are with check in checkboxes, but it may affect more characters, like radio buttons during checkout as someone else on this forum suggested.

Also, users are still reporting issues with Ocean WP 1.7.3

- https://wordpress.org/support/topic/icons-not-loading-4/
- https://wordpress.org/support/topic/check-icon-in-contact-form/

Thank you

**Comment by watchpci** [comment] 2019-11-14 16:16
Many thanks for the open ticket

for the devellopers, you can try with Pingdom or GTMETRIX, this indepence of customers
screenshots of these can show you that your icons do not display correctly

![téléchargement](https://user-images.githubusercontent.com/34822934/68875095-89b6a980-0702-11ea-8899-e0b31c482524.png)

**Comment by watchpci** [comment] 2019-11-14 16:21
the problem is OceanWP 1.7.2 or 1.7.3

i have the original website with OceanWP 1.7.1 and OceanWP Extra 1.5.19
and this fine
www.watchpci.com

but the mirror www-staging.watchpci.com with OceanWP 1.7.3 and OceanWP extra 1.5.19 this not good

Main-style.css
all-min.css

the environment of font awesome is bad.

**Comment by watchpci** [comment] 2019-11-18 08:43
please do not use your browser, but rather snapshot copiers, for example the OceanWP button

sample
https://www.site-shot.com/G0n4zgneEeqNPgJCrBEABA

https://shrinktheweb.snapito.io/v2/webshot/spu-ea68c8-ogi2-3cwn3bmfojjlb56e?size=800x0&screen=1024x768&url=https%3A%2F%2Fwww-staging.watchpci.com%2Fwishlist%2F


website of snapshot
https://screenshot.guru/
https://snapito.com/
https://www.site-shot.com/
https://www.screenshotmachine.com/
https://www.url2png.com/

**Comment by watchpci** [comment] 2019-11-18 19:33
workaround

modify function.php of the theme OceanWP

line 389
// Load font awesome style
		wp_enqueue_style( 'fontawesome', OCEANWP_THEME_URI .'/assets/fonts/fontawesome/css/all.min.css', false, '5.11.2' );
		wp_enqueue_style( 'font-awesome', $dir .'third/font-awesome.min.css', false, '4.7.0' );

**Comment by MarkHollo** [comment] 2020-01-12 09:29
Hello @Okkx and  @watchpci,

The issue with check boxes was fixed with the OceanWP 1.7.4 and Ocean Extra 1.5.20 update, so if you have used custom CSS to fix the issue temporarily, you can delete it.

Also, this doc might be of use to you: https://docs.oceanwp.org/article/637-icons-missing-after-font-awesome-5-upgrade

Hope this helps.

Best of luck with your website

**Closed by MarkHollo** 2020-01-12 09:29 UTC
